// Mocks generated by Mockito 5.0.7 from annotations
// in fake_terminal/test/terminal/widgets/internal/top_menu_widget_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:fake_terminal/theme/models/theme_settings.dart' as _i5;
import 'package:fake_terminal/theme/providers/theme_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [ThemeNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeNotifier extends _i1.Mock implements _i2.ThemeNotifier {
  MockThemeNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get initializationComplete =>
      (super.noSuchMethod(Invocation.getter(#initializationComplete),
          returnValue: Future<dynamic>.value(null)) as _i3.Future<dynamic>);
  @override
  set onError(_i4.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);
  @override
  _i3.Stream<_i5.ThemeSettings> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i5.ThemeSettings>.empty())
          as _i3.Stream<_i5.ThemeSettings>);
  @override
  _i5.ThemeSettings get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i5.ThemeSettings.dark) as _i5.ThemeSettings);
  @override
  set state(_i5.ThemeSettings? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  _i5.ThemeSettings get debugState =>
      (super.noSuchMethod(Invocation.getter(#debugState),
          returnValue: _i5.ThemeSettings.dark) as _i5.ThemeSettings);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void toggleTheme() => super.noSuchMethod(Invocation.method(#toggleTheme, []),
      returnValueForMissingStub: null);
  @override
  _i4.RemoveListener addListener(_i4.Listener<_i5.ThemeSettings>? listener,
          {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i4.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}
