name: fake_terminal
description: This is a fake terminal application. It has a predefined command
  list and simulates executing input as a Bash interpreter.
version: 2.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  logging: 1.1.1
  riverpod: 2.2.0
  flutter_riverpod: 2.2.0
  shared_preferences: 2.0.17
  json_annotation: 4.8.0
  json_serializable: 6.6.1
  http: 0.13.5
  sizer: 2.0.15
  equatable: 2.0.5
  url_launcher: 6.1.9
  file: ^6.1.4

dev_dependencies:
  mockito: 5.3.2
  test: ^1.21.1
  analyzer: 5.5.0
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/fake_data.json
  fonts:
    - family: FiraCode
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
  plugin:
    platforms:
      web:
        pluginClass: JavascriptDomPlugin
        fileName: plugins/javascript_dom/javascript_dom_web_plugin.dart
