name: fake_terminal
description: This is a fake terminal application. It has a predefined command
  list and simulates executing input as a Bash interpreter.
version: 2.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: 1.0.1
  riverpod: 0.14.0+1
  flutter_riverpod: 0.14.0+1
  shared_preferences: 2.0.5
  json_annotation: 4.0.1
  json_serializable: 4.1.0
  http: 0.13.1
  sizer: 2.0.11
  equatable: 2.0.0
  url_launcher: 6.0.7

dev_dependencies:
  mockito: 5.0.7
  test: ^1.16.8
  flutter_test:
    sdk: flutter
  build_runner: 1.12.2

flutter:
  uses-material-design: true
  assets:
    - assets/fake_data.json
  fonts:
    - family: FiraCode
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
  plugin:
    platforms:
      web:
        pluginClass: JavascriptDomPlugin
        fileName: plugins/javascript_dom/javascript_dom_web_plugin.dart
