// Mocks generated by Mockito 5.3.2 from annotations
// in fake_terminal/test/theme/providers/theme_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fake_terminal/theme/models/stored_theme.dart' as _i4;
import 'package:fake_terminal/theme/repositories/theme_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ThemeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeRepository extends _i1.Mock implements _i2.ThemeRepository {
  MockThemeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.StoredTheme?> fetchThemeSettings() => (super.noSuchMethod(
        Invocation.method(
          #fetchThemeSettings,
          [],
        ),
        returnValue: _i3.Future<_i4.StoredTheme?>.value(),
      ) as _i3.Future<_i4.StoredTheme?>);
  @override
  _i3.Future<void> saveThemeSettings(_i4.StoredTheme? theme) => (super.noSuchMethod(
        Invocation.method(
          #saveThemeSettings,
          [theme],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
