name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format:
      name: Format
      runs-on: ubuntu-latest
      container: cirrusci/flutter:stable

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Check format
          working-directory: ./src/fake_terminal
          run: flutter format --line-length=120 -n . | grep -v "**.mocks.dart" | grep -v "**.g.dart"

  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        working-directory: ./src/fake_terminal
        run: flutter pub get
      - name: Lint using flutter analyze
        working-directory: ./src/fake_terminal
        run: flutter analyze

  build_runner:
    name: build_runner
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        working-directory: ./src/fake_terminal
        run: flutter pub get
      - name: Remove generated code - JSON
        run: find . -name "*.g.dart" -exec rm -rf {} \;
      - name: Remove generated code - Mocks
        run: find . -name "*.mocks.dart" -exec rm -rf {} \;
      - name: Generate code using build_runner
        working-directory: ./src/fake_terminal
        run: flutter pub run build_runner build >/dev/null
      - name: Check there is no differences
        working-directory: ./src/fake_terminal
        run: git status --porcelain

  test:
    name: Test
    needs: [lint, format, build_runner]
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get dependencies
        working-directory: ./src/fake_terminal
        run: flutter pub get
      - name: Run all tests
        working-directory: ./src/fake_terminal
        run: flutter test --reporter=expanded --coverage